### PR TITLE
Various README fixes

### PR DESCRIPTION
**Pull request by jneidel**
See commits.

> store the file a csv file is used (datas.csv)

["data" is already plural](https://www.thoughtco.com/what-is-the-plural-of-data-3126317) :smile:

> it is a sort of hierarchy you can access/view all notes in class it has 3 classes;

I have no idea what you are trying to say here.

> containing only 6 functions

Proceeds to list 8 commands :)

> `<br>`

In markdown most of the time you just use empty lines

---

You should create a pip package for easier install.

Instead of writing out the TOC manually with comments, use a tool like `doctoc` (we use it in [awesome-cli-apps](https://raw.githubusercontent.com/agarrharr/awesome-cli-apps/master/readme.md)).

### CODE REVIEW

**Comment by ThDag** [comment]
thank you so much for the first ever (i think) contribution to my project. it really means a lot to me.

- firstly i don't get the "plural of data" 

- when i made class feature i thought of it as a general purpose feature where anyone can use it anyway they want; grouping or priority.
And i made it like financial classes where first is the highest and lower (3) is the lowest like the importance of a note. 
 

- I have forgot about that number i constantly add new features but documentation is forgotten.

- I used the '<br>' because it was showing in the same line but if you are sure that isn't happening we should indeed remove it 

- i don't know much about pip packages i will research in the future it would be great if you explained more

- I indeed use a automatic TOC so there is that.

Thank you so much again your pull request is great and i will merge it but i wanted to talk about the changes first

**Comment by jneidel** [comment]
> * firstly i don't get the "plural of data"

"datas" is wrong in english since "data" is already the plural. No need to add an s

> * when i made class feature i thought of it as a general purpose feature where anyone can use it anyway they want; grouping or priority.

Sure, in the README its just not explained very well I feel :smile:

> * I have forgot about that number i constantly add new features but documentation is forgotten.

Which is why you shouldn't put a number there. Documentation can a liability if it is lying to you.

> * i don't know much about pip packages i will research in the future it would be great if you explained more

Makes it easier to install. Check out this [official guide](https://packaging.python.org/en/latest/tutorials/packaging-projects/) or just google around.

> * I indeed use a automatic TOC so there is that.

I'd still switch to doctoc, having comments all other the place looks really messy to me :)

**Comment by ThDag** [comment]
> "datas" is wrong in english since "data" is already the plural. No need to add an s

Yep i just added "change datas to data" in my todo list 😃

> Sure, in the README its just not explained very well I feel 

I mean. Some of the things in the README are same as when i wrote them first with no care.
So i think i should rewrite the README which i doubt that i will 😅 

> Which is why you shouldn't put a number there. Documentation can a liability if it is lying to you.

That makes sense i shouldn't make documentation liability by adding changing variables. Which i didn't thought about it before. And that's why i really care about feedback, you learn new stuff. Thanks again.

> Makes it easier to install. Check out this official guide or just google around.

I will research and hopefully implant that. I actually had heard that from somebody else but i didn't prioritized it. Will read that for sure.

> I'd still switch to doctoc, having comments all other the place looks really messy to me :)

Yeah it looks messy. i just copy pasted my whole README into some TOC website and pasted it back to repo. which i felt that it wasn't the more *reasonable* way to do it but i just shrunken shoulders to it. i will switch to doctoc thank you again. ❤️

**Comment by ThDag** [comment]
Im merging indeed. thank you

**Pull request merged**
